 version: "3"

 services:
  app:
    build:
      context: .
    ports:
      #host:container
      - "8000:8000"
    volumes:
      #host:container
      - ./app:/app
    command: >
      sh -c "python maange.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000" 
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=kimchikimchi
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kimchikimchi